# Generated by Django 2.2.10 on 2020-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200520_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ptProvince',
            field=models.CharField(default='QUan', max_length=50),
            preserve_default=False,
        ),
    ]
